name = "pwa-line-reminder"
main = "worker.js"
compatibility_date = "2026-09-29"
workers_dev = true

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "rex-line-reminder"
database_id = "629b319b-0cb6-4ebe-a684-d524153bf709"

[vars]
APP_ORIGIN = "https://lihe-source.github.io"
